# Use root/example as user/password credentials
version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"

    # admin : pass
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081

    # guest : guest
    rabbitmq:
        image: rabbitmq:3-management
        hostname: local-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        
        
    