version: '3.8'

services:    
    mongodb:
        image: mongo:latest
        healthcheck:
            test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 1s
            timeout: 10s
            retries: 10
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    rabbitmq:
        image: masstransit/rabbitmq:latest
        healthcheck:
            test: [ "CMD", "rabbitmqctl", "status" ]
            interval: 3s
            timeout: 10s
            retries: 10
        # environment:
        #     RABBITMQ_DEFAULT_USER: guest
        #     RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672