version: '3.8'

services:
    # webapp:
    #     image: fluxo-caixa:latest
    #     build:
    #         context: ..
    #     ports:
    #         - 5000:5000
    #     depends_on:
    #         - mongodb
    #         - rabbitmq
    #     environment:
    #         ASPNETCORE_ENVIRONMENT: Development
    #         ASPNET_MONGO_CONNECTION_STRING: mongodb://root:example@mongodb:27017
    #         ASPNET_MONGO_DATABASE: CASH-FLOW
    #         ASPNET_RABBITMQ_CONNECTION_STRING: rabbitmq
    #         ASPNET_RABBITMQ_QUEUE: CASH-FLOW-ENTRIES
    #         ASPNETCORE_HTTP_PORTS: 5000

    mongodb:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongodb    

    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:            
            - 5672:5672
            - 15672:15672